server:
  port: 8222

spring:
  application:
    name: go-api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          # Must create a route for each microservice.
          # The API Gateway will use Eureka + Spring Cloud LoadBalancer to resolve the service ID (lb://SERVICE-ID) to
          # the correct instance(s) & then forward the request.
          routes:
            - id: go-user-service
              uri: lb://GO-USER-SERVICE
              predicates:
                - Path=/api/v1/user/**
            - id: go-team-service
              uri: lb://GO-TEAM-SERVICE
              predicates:
                - Path=/api/v1/teams/**,/api/v1/invites/**
            - id: go-league-service
              uri: lb://GO-LEAGUE-SERVICE
              predicates:
                - Path=/api/v1/leagues/**,/api/v1/payments/**
            - id: go-messaging-service-ws
              uri: lb:ws://GO-MESSAGING-SERVICE
              predicates:
                - Path=/api/v1/messaging/ws
              filters:
                - SetPath=/ws
            - id: go-messaging-service
              uri: lb://GO-MESSAGING-SERVICE
              predicates:
                - Path=/api/v1/messaging/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://one-magpie-92.clerk.accounts.dev
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      default-zone: http://go-discovery-service:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
