spring:
  application:
    name: go-league-service

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    table: league_flyway_history
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${CLERK_ISSUER_URI}

  kafka:
    # Only the generic Kafka config here; bootstrap server is env/profile specific
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.trusted.packages: "com.game.on.common.dto,com.game.on.*"
      spring.json.value.default.type: com.game.on.common.dto.PaymentDTO
      spring.json.use.type.headers: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
