spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:gameon_db}
    username: ${DB_USER:username}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    table: league_flyway_history
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://one-magpie-92.clerk.accounts.dev

  kafka:
    # Config to run Docker Kafka from local
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    # Config to run deployed kafka from local (keep commented out if running Docker Kafka)
#    bootstrap-servers: ${KAFKA_BOOTSTRAP:kafka-1f7f0718-game-on.d.aivencloud.com:25817}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.trusted.packages: "com.game.on.common.dto,com.game.on.*"
      spring.json.value.default.type: com.game.on.common.dto.PaymentDTO
      spring.json.use.type.headers: false

      # Config to test deployed Kafka from local (keep commented out if running Docker Kafka)
#      security.protocol: SSL
#      ssl.keystore.type: PKCS12
#      ssl.keystore.location: ${KAFKA_KEYSTORE_PATH}
#      ssl.keystore.password: ${KAFKA_KEYSTORE_PASSWORD}
#      ssl.truststore.type: JKS
#      ssl.truststore.location: ${KAFKA_TRUSTSTORE_PATH}
#      ssl.truststore.password: ${KAFKA_TRUSTSTORE_PASSWORD}
server:
  port: 8093

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
  client:
    register-with-eureka: true
    fetch-registry: true 
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
