spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gameon_db
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    table: league_flyway_history
    locations: classpath:db/migration

server:
  port: 8093

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
