spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:gameon_db}
    username: ${DB_USER:username}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    table: team_flyway_history
    locations: classpath:db/migration
    repair: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${CLERK_URL:https://one-magpie-92.clerk.accounts.dev}

server:
  port: 8094

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
  client:
    register-with-eureka: true
    fetch-registry: true 
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

aws:
  region: ${AWS_REGION:us-east-1}
  endpoint:
    url: ${AWS_ENDPOINT_URL:}
  s3:
    bucket: gameon-db
