import { StyleSheet } from 'react-native';
import { Fonts } from './theme';

export const exploreStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  topGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 700,
  },
  searchContainer: {
    paddingHorizontal: 20,
    paddingBottom: 5,
  },
  SearchWrapper: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    borderRadius: 25,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  SearchInput: {
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: Fonts.rounded,
    marginLeft: 12,
    marginRight: 8,
  },
  clearButton: {
    padding: 4,
  },
  searchBarContainer: {
    backgroundColor: 'transparent',
    borderTopWidth: 0,
    borderBottomWidth: 0,
    paddingHorizontal: 0,
  },
  searchBarInputContainer: {
    backgroundColor: '#1C2A3A',
    borderRadius: 25,
    height: 50,
    borderWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#ffffff20',
  },
  searchBarInput: {
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: Fonts.rounded,
  },
  searchInputWrapper: {
    backgroundColor: '#1c1c1cff',
    borderRadius: 28,
    paddingVertical: 14,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#404040',
  },
  searchIcon: {
    marginRight: 12,
    opacity: 0.8,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  teamsList: {
    flex: 1,
  },
  teamsListContent: {
    paddingHorizontal: 24,
    paddingBottom: 20,
  },
  teamItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1C2A3A',
    paddingVertical: 16,
    paddingHorizontal: 16,
    marginBottom: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#2A3A4A',
  },
  teamInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  teamLogo: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#2A3A4A',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  logoText: {
    fontSize: 24,
  },
  teamDetails: {
    flex: 1,
  },
  teamName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 2,
    fontFamily: Fonts.rounded,
  },
  teamLeague: {
    fontSize: 14,
    color: '#FFFFFF80',
    fontWeight: '500',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  placeholder: {
    width: 40,
  },
  searchResultsList: {
    flex: 1,
  },
  searchResultsContent: {
    paddingHorizontal: 30,
    paddingTop: 5,
  },
  searchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#062031ff',
    paddingVertical: 10,
    paddingHorizontal: 18,
    marginBottom: 12,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  searchResultInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  searchResultLogo: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
  },
  searchResultLogoText: {
    fontSize: 20,
  },
  searchResultDetails: {
    flex: 1,
  },
  searchResultName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 2,
    fontFamily: Fonts.rounded,
  },
  searchResultSubtitle: {
    fontSize: 14,
    color: '#FFFFFF80',
    fontWeight: '500',
  },
});