CREATE TABLE IF NOT EXISTS public.sport_table
(
    sport_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_name VARCHAR(255) NOT NULL UNIQUE,
    players_per_team SMALLINT NOT NULL CHECK (players_per_team > 0)
);
