spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: postgres
    password: password123!
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8090

