spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gameon_db
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/gameon

      client:
        registration:
          keycloak-admin:
            provider: keycloak
            client-id: gameon-client
            client-secret: uYkNTIU9pcffRmuGxzvWKgo2uTTC2R4L
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/gameon/protocol/openid-connect/token

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

keycloak:
  base-url: http://localhost:8080
  realm: gameon
