spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://go-discovery-service:8761/eureka/