ALTER TABLE teams
    ADD COLUMN IF NOT EXISTS total_points INTEGER NOT NULL DEFAULT 0;

ALTER TABLE teams
    ADD COLUMN IF NOT EXISTS total_matches INTEGER NOT NULL DEFAULT 0;

ALTER TABLE teams
    ADD COLUMN IF NOT EXISTS win_streak INTEGER NOT NULL DEFAULT 0;

ALTER TABLE teams
    ADD COLUMN IF NOT EXISTS minutes_played INTEGER NOT NULL DEFAULT 0;

ALTER TABLE team_match_scores
    ADD COLUMN IF NOT EXISTS official_end_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
